# Generated by Django 5.2.5 on 2025-09-12 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler')], max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('min_order_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('wholesale_discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gstin', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_doc', models.FileField(blank=True, null=True, upload_to='docs/gst/')),
                ('trade_license', models.FileField(blank=True, null=True, upload_to='docs/licenses/')),
                ('is_verified', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'indexes': [models.Index(fields=['user_type'], name='accounts_cu_user_ty_59002e_idx'), models.Index(fields=['is_verified'], name='accounts_cu_is_veri_dbe40f_idx')],
            },
        ),
    ]
