# Generated by Django 5.2.5 on 2025-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='accounts_cu_user_ty_59002e_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='accounts_cu_is_veri_dbe40f_idx',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='gst_doc',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='min_order_qty',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='trade_license',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='wholesale_discount_pct',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
