# Generated by Django 5.2.5 on 2025-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customerprofile_accounts_cu_user_ty_59002e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
