# Generated by Django 5.2.5 on 2025-10-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='supports_doorstep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='supports_hub',
            field=models.BooleanField(default=True),
        ),
    ]
