# Generated by Django 5.2.5 on 2025-09-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysize',
            options={'ordering': ['order', 'size__name']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='size',
            name='order',
        ),
    ]
