# Generated by Django 5.2.5 on 2025-09-30 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_hero_topbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ratio', models.CharField(help_text='e.g., 1:1:1 or S,M,L', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moq_options', to='catalog.product')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
