# Generated by Django 5.2.5 on 2025-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_moqoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moqoption',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='moqoption',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='moqoption',
            name='ratio',
        ),
        migrations.AddField(
            model_name='moqoption',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
    ]
