# Generated by Django 5.2.5 on 2025-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_moqoption_options_remove_moqoption_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.fabric'),
        ),
    ]
