# Generated by Django 5.2.5 on 2025-08-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_minimum_order_qty'),
        ('catalog', '0006_drop_legacy_product_columns'),
    ]

    operations = [
    ]
