# Generated by Django 5.2.5 on 2025-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_total_value_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pack_details',
            field=models.CharField(blank=True, help_text='Stores the selected pack/MOQ details', max_length=100, null=True),
        ),
    ]
