# Generated by Django 5.2.5 on 2025-10-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('doorstep', 'Doorstep Delivery'), ('hub', 'Nearest Hub Delivery')], max_length=20, null=True),
        ),
    ]
